[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tlink.ld",
    "-C", "link-arg=-z",
    "-C", "link-arg=max-page-size=0x1000",
    "-C", "link-arg=-Map=kernel.map",
    "-C", "code-model=large",
    "-C", "relocation-model=static",
]
linker = "rust-lld"

# Custom test runner that boots the test binary in QEMU
runner = "scripts/test_runner.sh"

[alias]
check = "check --target x86_64-unknown-none"
build = "build --target x86_64-unknown-none"
run = "run --target x86_64-unknown-none"
